### ISSUE TITLE
Use the original TD3 Actors and Critics

### ISSUE THREAD

**Issue by EE-LiuYunhao** [wwwCielwww/MADDPG#2]
### Refactor the Actors and Critics

Use the TD3 original actor and critic to implement the A-C algorithm

---
### The reason to do so
1. Higher robustness
1. More adaptive network structure
1. Easier for store and re-use the trained policy and re-training (and even evolution) 
### TODOs
- [x] Encapsulate multiple TD3 actors into our Actor class and coordinate them
- [x] Customize the original off-policy critic algorithm
- [x] Adapt the existing framework with the modified classes
### Developmer
@EE-LiuYunhao

**Comment by EE-LiuYunhao** [comment]
### Progress blocked . 

Needing first to figure out what we need to modify regarding the original TD3 framework.

**Comment by EE-LiuYunhao** [comment]
### Resume the development

On the branch `dev_td3_actor_critic`
